version: "2"

networks:
  mail:
    driver: bridge

services:
    server:
      build:
         context: .
         dockerfile: postfix
      ports:
         - "25:25"
         - "465:465"
         - "587:587"
      volumes:
         - /home/docker/mail/mail.log:/var/log/mail.log
         - /home/docker/mail/spool/:/var/spool/postfix
      networks:
         - mail
