networks:
  cloud:
    driver: bridge

nginx:
    image: wonderfall/boring-nginx
    container_name: nginx
    restart: always
    links:
      - nextcloud:nextcloud
    ports:
      - "80:8000"
      - "443:4430"
    volumes:
      - /home/docker/nginx/sites-enabled:/sites-enabled
      - /home/docker/nginx/conf:/conf.d
      - /home/docker/nginx/log:/var/log/nginx
      - /home/docker/nginx/certs:/certs
      - /home/docker/nginx/passwd:/passwds
      - /home/docker/nginx/www:/www
      - /home/docker/letsencrypt/live:/letsencrypt
    environment:
      - UID=1000
      - GID=1000
    networks:
      - cloud
nextcloud:
    image: wonderfall/nextcloud
    container_name: nextcloud
    restart: always
    links:
      - db_nextcloud:db_nextcloud
    environment:
      - UID=1000
      - GID=1000
    volumes:
      - /home/docker/nextcloud/data:/data
      - /home/docker/nextcloud/config:/config
      - /home/docker/nextcloud/apps:/apps2
    networks:
      - cloud
db_nextcloud:
      image: mariadb:10
      container_name: db_nextcloud
      restart: always
      ports:
       - "3306:3306"
      volumes:
       - /home/docker/nextcloud/db:/var/lib/mysql
      networks:
       - cloud
      environment:
       - MYSQL_ROOT_PASSWORD=supersecretpassword
       - MYSQL_DATABASE=nextcloud
       - MYSQL_USER=nextcloud
       - MYSQL_PASSWORD=supersecretpassword
