version: '2'

networks:
  vpnui:
    driver: bridge

services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: awalach/openvpn
    networks:
     - vpnui
    container_name: openvpn
    ports:
     - "1194:1194/udp"
    restart: always
    depends_on:
      - "gui"
    volumes:
     - /home/docker/vpnwebui/data/conf:/etc/openvpn
  gui:
    image: awalach/openvpn-web-ui
    container_name: openvpn-gui
    ports:
     - "8181:8080/tcp"
    networks:
     - vpnui
    restart: always
    volumes:
     - /home/docker/vpnwebui/data/conf:/etc/openvpn
     - /home/docker/vpnwebui/db:/opt/openvpn-gui/db
